article:
   path: /article/list
   controller: App\Controller\ArticleController::index
addarticle:
   path: /article/add
   controller: App\Controller\ArticleController::add

dashboard:
   path: /dashboard
   controller: App\Controller\DashboardController::index 

category:
   path: /category
   controller: App\Controller\CategoryController::index  

comment:
   path: /article/comment/{articleId}
   controller: App\Controller\ArticleController::preview      

addcomment:
   path: /article/comment/add/{articleId}
   controller: App\Controller\CommentController::add          
